config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'welcome#home'
  get 'about', to: 'welcome#about'
  
  get '/s/:slug', to: 'links#view', as: :short
  
  resources :articles
  resources :links
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence:true, length: {minimum: 3, maximum: 50}
  validates :description, presence:true, length: {minimum: 10, maximum: 300}
end

app/models/link.rb
class Link < ActiveRecord::Base

  validates :url, presence:true, length: {in: 3..255, too_long: "too long", too_short: "too short"}, on: :create, format: URI::regexp(%w[http https])
  validates :slug, uniqueness: true, length: {in: 3..255, too_long: "too long, maximum %{count} characters", too_short: "too short, minimum %{count} characters"}, on: :create
  
  # def short
  #   Rails.application.routes.url_helpers.short_url(slug: self.slug)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  
  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @article.update(article_params)
     flash[:notice] = "Article was successfully updated"
     redirect_to article_path(@article)
    else
     render 'edit'
    end
  end
  
  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :description)
    end
    
    def set_article
      @article = Article.find(params[:id])
    end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  before_action :set_link, only: [:edit, :update, :show, :destroy]
  
  def index
    @links = Link.all
  end
  
  def new
    @link = Link.new
  end
  
  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = "Link was successfully created"
      redirect_to link_path(@link)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def show
  end
  
  def view
    @link = Link.find_by(slug: params[:slug]) 
    if @link.nil?
      redirect_to root_path
    else
      @link.update_attribute(:clicked, @link.clicked + 1)
      redirect_to @link.url
    end
  end
  
  def update
    if @link.update(link_params)
    flash[:notice] = "Link was successfully updated"
    redirect_to link_path(@link)
    else
    render 'edit'
    end
  end
  
  def destroy
    @link.destroy
    flash[:notice] = "Link was successfully deleted"
    redirect_to links_path
  end
  
  private
    def link_params
      params.require(:link).permit(:url, :slug, :clicked)
    end
    
    def set_link
      @link = Link.find(params[:id])
    end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def home
    end 
    
    def about
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h3>The following errors prevented the article from saving</h3>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>

  <p>
      <%= f.label :title %><br />
      <%= f.text_field :title %> 
  </p>
  <p>
    <%= f.label :description %> <br />
    <%= f.text_area :description %>  
  </p>
  <p>
   <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to all articles", articles_path %>

app/views/articles/edit.html.erb
<h1>Edit the selected article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All articles</h1>

<p>
  <%= link_to "Create new article", new_article_path %>
</p>
<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Show</th>
        <th>Edit</th>
        <th>Destory</th>
    </tr>
    
    <% @articles.each do |article| %>
    <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <th><%= link_to "Show", article_path(article) %></th>
        <th><%= link_to "Edit", edit_article_path(article) %></th>
        <th><%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you Sure?"} %></th>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1>Create an Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Show the selected article</h1>

<p>
    Title: <%= @article.title %>
</p>
<p>
    Description: <%= @article.description %>
</p>


<th><%= link_to "Edit this article", edit_article_path(@article) %></th> | 
<%= link_to "Back to all articles", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRubyApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<% if @link.errors.any? %>
<h3>The following errors prevented the link from saving</h3>
<ul>
  <% @link.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_for @link do |f| %>

  <p>
      <%= f.label :URL %><br />
      <%= f.text_field :url %> 
  </p>
  <p>
    <%= f.label :Short %> <br />
    <%= f.text_area :slug %>  
  </p>
  <p>
   <%= f.submit %>
  </p>

<% end %>

<%= link_to "Back to all link", links_path %>

app/views/links/edit.html.erb
<h1>Edit the selected link</h1>

<%= render 'form' %>

app/views/links/index.html.erb
<h1>All links</h1>

<p>
  <%= link_to "Create new link", new_link_path %>
</p>

<table>
    <tr>
        <th>URL</th>
        <th>Short URL</th>
        <th>Number of visits</th>
    </tr>
    
    <% @links.each do |link| %>
    <tr>
        <td><%= link.url %></td>
        <td><%= link.slug %></td>
        <td><%= link.clicked %></td>
        <th><%= link_to "View", short_path(link.slug) %></th>
        <th><%= link_to "Show", link_path(link) %></th>
        <th><%= link_to "Edit", edit_link_path(link) %></th>
        <th><%= link_to "Delete", link_path(link), method: :delete, data: {confirm: "Are you Sure?"} %></th>
    </tr>
    <% end %>
</table>

app/views/links/new.html.erb
<h1>Create a link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<h1>Show the selected link</h1>

<p>
    URL: <%= @link.url %>
</p>
<p>
    Short URL: <%= @link.slug %>
</p>
<p>
    Number of visits: <%= @link.clicked %>
</p>

<th><%= link_to "Edit this link", edit_link_path(@link) %></th> | 
<th><%= link_to "Back to all links", links_path %><th> 

app/views/welcome/about.html.erb
<h1>Welcome About Page</h1>

<%= link_to 'Home', root_path %>

<h2>Test image</h2>

<%= link_to image_tag('mona.jpg'), root_path %>

app/views/welcome/home.html.erb
<h1>Welcome Home</h1>


<%= link_to 'Articles', articles_path %> | 

<%= link_to 'About', about_path %> |

<%= link_to 'Links', links_path %>